# Generated by Django 6.0.2 on 2026-02-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text="Short team tag/abbreviation",
                max_length=10,
                unique=True,
            ),
        ),
    ]
